// Code generated by logcopter-gen; DO NOT EDIT.

package sanitizecli

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.sanitize.internal.cli")
